server.servlet.context-path=/workintech
server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5433/kutuphane
spring.datasource.username=postgres
spring.datasource.password=6768
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE